export default [
  {
    id: 1,
    name: 'Vincent Van Dogh',
    raca: 'Shitzu',
    cor: 'Amarelo',
    olhos: 'Castanhos',
    tamanho: '45cm',
    pelo: 'Longo',
    orelha: 'Média',
    cauda: 'Curta',
    mapa: 'Ver localização',
    image: 'https://placekitten.com/640/319'
  },
  {
    id: 2,
    name: 'Frango Simoncelo',
    raca: 'SRD',
    cor: 'Laranja',
    olhos: 'Preto',
    tamanho: '45cm',
    pelo: 'Curto',
    orelha: 'Pequena',
    cauda: 'Curta',
    mapa: 'Ver localização',
    image: 'https://placekitten.com/640/371'
  },
  {
    id: 3,
    name: 'Blue',
    raca: 'Shitzu',
    cor: 'Amarelo',
    olhos: 'Castanhos',
    tamanho: '45cm',
    pelo: 'Longo',
    orelha: 'Média',
    cauda: 'Curta',
    mapa: 'Ver localização',
    image: 'https://placekitten.com/640/318'
  },
  {
    id: 4,
    name: 'Zeca',
    raca: 'Shitzu',
    cor: 'Amarelo',
    olhos: 'Castanhos',
    tamanho: '45cm',
    pelo: 'Longo',
    orelha: 'Média',
    cauda: 'Curta',
    mapa: 'Ver localização',
    image: 'https://placekitten.com/640/350'
  },
  {
    id: 5,
    name: 'Renatinho',
    raca: 'Shitzu',
    cor: 'Amarelo',
    olhos: 'Castanhos',
    tamanho: '45cm',
    pelo: 'Longo',
    orelha: 'Média',
    cauda: 'Curta',
    mapa: 'Ver localização',
    image: 'https://placekitten.com/640/360'
  },
  {
    id: 6,
    name: 'Zé',
    raca: 'Shitzu',
    cor: 'Amarelo',
    olhos: 'Castanhos',
    tamanho: '45cm',
    pelo: 'Longo',
    orelha: 'Média',
    cauda: 'Curta',
    mapa: 'Ver localização',
    image: 'https://placekitten.com/640/312'
  },
  {
    id: 7,
    name: 'Tico',
    raca: 'Shitzu',
    cor: 'Amarelo',
    olhos: 'Castanhos',
    tamanho: '45cm',
    pelo: 'Longo',
    orelha: 'Média',
    cauda: 'Curta',
    mapa: 'Ver localização',
    image: 'https://placekitten.com/640/309'
  },
  {
    id: 8,
    name: 'Marley',
    raca: 'Shitzu',
    cor: 'Amarelo',
    olhos: 'Castanhos',
    tamanho: '45cm',
    pelo: 'Longo',
    orelha: 'Média',
    cauda: 'Curta',
    mapa: 'Ver localização',
    image: 'https://placekitten.com/640/311'
  },
  {
    id: 9,
    name: 'Kika',
    raca: 'SRD',
    cor: 'Preto e amarelo',
    olhos: 'Castanhos',
    tamanho: '90cm',
    pelo: 'Curto',
    orelha: 'Média',
    cauda: 'Grande',
    mapa: 'Ver localização',
    image: 'https://placekitten.com/640/340'
  }
]
